defaults:
  - base
  - _self_
  - server: star04

general:
  exp_name: 'firepbt_fmnist_16'
  exp_desc: 'n steps 30 | AMP | aug_ops 1, aug_mag 10'
  seed_base: 71173

  num_cpus: 1
  num_gpus: 0.33

algo:
  _target_: algo.firepbt.FirePBT
  pop1_size: 8
  pop2_size: 8
  popEval_size: 6

  quant_top: 0.25
  quant_bottom: 0.25
  perturb_factor: 2.0

  min_steps_before_eval:
    1: 0
    2: 1660
  max_eval_steps: 4980

  t_step: 1660
  t_max: 49800

task:
  _target_: task.classification_amp.ClassificationTask
  t_eval: 166 # only FirePBT needs intermediate values and so has this != t_step.
  viz: False
  data:
    name: FashionMnist
    n_classes: 10
    n_channels: 1
    val_size: 10000

    rand_aug_n_ops: 1
    rand_aug_mag: 10

    batch_size: 128
    num_workers: 2

  model:
    _target_: model.resnet12.ResNet12
    output_size: ${task.data.n_classes}
    channels: ${task.data.n_channels}
    dropblock_dropout: 0.0
    avg_pool: True

  optimizer:
    name: SGD
    lr: 0.1
    momentum: 0.0
    weight_decay: 0.0005

search_space:
  _target_: search_space.cs.ConfigSpaceSearchSpace
  hyperparameters:
    - name: log10_lr
      type: Float
      distribution: Uniform
      bounds: [ -6, 0 ]