defaults:
  - base
  - _self_
  - server: star04

general:
  exp_name: 'bgpbt_toydeceptive_00'
  exp_desc: ' '
  seed_base: 71173

algo:
  _target_: algo.bgpbt.BGPBT
  pop_size: 22
  n_init: ${algo.pop_size}

  quant_top: 0.25
  quant_bottom: 0.25
  perturb_factor: 2.0

  t_step: 20
  t_max: 1000

task:
  _target_: task.toy_deceptive.ToyDeceptiveTask
  t_max: ${algo.t_max}
  noise_std: null


search_space:
  _target_: search_space.cs.ConfigSpaceSearchSpace
  hyperparameters:
    - name: lr
      type: Float
      distribution: Uniform
      bounds: [ 1e-4, 1.1 ]
      log: False