_target_: algo.firepbt.FirePBT
name: 'firepbt'
pop1_size: 3
pop2_size: 3
popEval_size: 2

quant_top: 0.34
quant_bottom: 0.34
perturb_factor: 2.0

min_steps_before_eval:
  1: 0
  2: 500
max_eval_steps: 1500

t_step: 500
t_eval: 50
t_max: 50000