_target_: algo.firepbt.FirePBT
name: 'firepbt'
pop1_size: 8
pop2_size: 8
popEval_size: 6

quant_top: 0.125
quant_bottom: 0.125
perturb_factor: 2.0

min_steps_before_eval:
  1: 0
  2: 15_000_000
max_eval_steps: 45_000_000

t_step: 15_000_000
num_evals_per_step: 10
t_max: 150_000_000