_target_: algo.firepbt.FirePBT
name: 'firepbt'
pop1_size: 8
pop2_size: 8
popEval_size: 6

quant_top: 0.25
quant_bottom: 0.25
perturb_factor: 2.0

min_steps_before_eval:
  1: 0
  2: 1_500_000
max_eval_steps: 4_500_000

t_step: 1_500_000
num_evals_per_step: 10
t_max: 150_000_000